# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  style_check:
    working_directory: /tmp/src/cis-processing
    docker:
      # Ubuntu 14.04 with Docker 17.10.0-ce
      - image: continuumio/miniconda3
    steps:
      - checkout
      - run:
          name: Generate environment
          command: |
            conda create -n venv python=2.7 pylint -yq
            source activate venv
            pip install 'flake8<3.0' flake8-putty
      - run:
          name: Run style check
          command: |
            source activate venv
            flake8 /tmp/src/cis-processing
workflows:
  version: 2
  run_style_check:
    jobs:
      - style_check
